"""empty message

Revision ID: 2ee0b1e771f1
Revises: 6743ce2704d5
Create Date: 2023-03-21 14:00:52.085596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee0b1e771f1'
down_revision = '6743ce2704d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soju', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_token', sa.String(), nullable=False))
        batch_op.drop_constraint('soju_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_token'], ['token'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soju', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('soju_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('user_token')

    # ### end Alembic commands ###
